### ISSUE TITLE
Docs failing to build for 2.0.0

### ISSUE THREAD

**Issue by superlou** [QuantumBadger/Speedy2D#105]
It looks like docs are failing to build per https://docs.rs/crate/speedy2d/2.0.0/builds/960409. That said, when I build master, that seems to succeed.

**Comment by MrLavender** [comment]
Is this ever going to be fixed? I'm looking for a simple cross-platform windowing/graphics crate and Speedy2D looks perfect, but then I click on the documentation link https://docs.rs/speedy2d and what I see is warnings about broken builds (which according the build logs has been like that since Nov 5 2023).

Doesn't exactly inspire any confidence that I should use this crate.

**Comment by QuantumBadger** [comment]
Thanks guys, I've pushed version 2.1.0 which addresses this: https://docs.rs/speedy2d/2.1.0/speedy2d/
