### ISSUE TITLE
Draw Rectangle Image Subset Without Tint

### ISSUE THREAD

**Issue by wyhinton** [QuantumBadger/Speedy2D#23]
Is the correct means of drawing a subset of a rectangle image _without_ tint to set the tint color to ```Color::TRANSPARENT```? 

i.e ```graphics.draw_rectangle_image_subset_tinted(sub_rect_screen, Color::TRANSPARENT, norm_rect, &base_image)```

**Comment by QuantumBadger** [comment]
The way to do this would be to use `Color::WHITE`. All four components of the image color (red, green, blue, alpha) get multiplied by the tint color.

Since all the components of white are 100% `(1, 1, 1, 1)`, tinting a color with white has no effect. Transparent means the alpha component is set to zero, so tinting an image with `Color::TRANSPARENT` would make the whole image transparent :)
