### ISSUE TITLE
How to send `FormattedTextBlock` between threads

### ISSUE THREAD

**Issue by superlou** [QuantumBadger/Speedy2D#90]
I'm trying to use Speedy2D in an application where the drawing operations for the `on_draw(...)` callback are pushed into a vec buffer by a scripting engine (Boa) in another thread. This works for simple operations that have parameters that are cheap to clone. However, the `FormattedTextBlock` isn't clonable or `send`. Is there a mechanism that can send this data between threads?

**Comment by QuantumBadger** [comment]
Thanks for the report. It looks like this is because I've used `Rc` for various things inside `FormattedTextBlock`, rather than `Arc`. Unfortunately this will be quite hard to fix without making various non-backwards-compatible changes to the API!

I'd consider doing a v2.0.0 release for this (and use that opportunity to clean up some other stuff, like the legacy GL code). Until then, unfortunately I think it'll be necessary to do the formatting inside `on_draw`, and just pass the string itself (plus some other options) between threads.

Might have a go at a fix (and v2.0.0) this weekend if I get time!

**Comment by QuantumBadger** [comment]
Doing a 2.0 release isn't a big deal, I've been meaning to do one for a while to get rid of the old dependency on the `gl` crate!

I've pushed a fix for this issue to `master` -- `FormattedTextBlock` is now cheaply cloneable and can be transferred between threads. Would you be able to give it a try please and confirm that the issue is fixed for you?

**Comment by superlou** [comment]
That's awesome! I was actually in the middle of refactoring my app to do the FormattedTextBlock creation in both the window drawing thread and the JS thread (with redundant buffers), but I'll try out this approach. I pull master into my fork for #88, then I can give it a shot. Is the `Arc` usage over `Rc` a performance hit to Speedy2D? I don't want this single use-case to limit the project's "speedy" goal.

**Comment by superlou** [comment]
Ok, I think I have it working at https://github.com/superlou/signrs/blob/2579f9a30e59affdfa15077eb6d6cb1e611e7f02/src/window_handler.rs#L170. I can clone `FormattedTextBlock`s from one thread into another. I'm sure I'm doing some terrible thread synchronization stuff, but the proof-of-concept seems to work fine.

**Comment by superlou** [comment]
@QuantumBadger, should I close this issue? From what I can tell it's working in version 2, though I don't know if there was any housekeeping things to do for this feature.

**Comment by QuantumBadger** [comment]
Thanks for the reminder -- I was waiting until I'd actually published the 2.0.0 release, and this is now done :) Closing the issue.
